version: '3.7'

services:

  agriculture_server:
    container_name: agriculture_server
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - ./src/sql/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    networks:
      - postgres-compose-network

  pgAdmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "postgres-admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: secret
    ports:
      - "16543:80"
    depends_on:
      - agriculture_server
    networks:
      - postgres-compose-network

  main:
    container_name: main
    build:
      context: .
      target: development
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - ${PORT}:${PORT}
    command: /bin/sh -c "yarn && yarn run start:dev"
    env_file:
      - .env
    depends_on:
      - agriculture_server
    networks:
      - postgres-compose-network

networks:
  postgres-compose-network:
    driver: bridge
volumes:
  pgdata: